config/routes.rb
Storied::Application.routes.draw do
  root :to => 'ideas#index'
  resources :characters, :controller => "ideas", :type=>"Character", 
    only: [:index, :new, :create, :show, :edit, :update]
  resources :items, :controller => "ideas", :type=>"Item",
    only: [:index, :new, :create, :show, :edit, :update]
  resources :locations, :controller => "ideas", :type=>"Location",
    only: [:index, :new, :create, :show, :edit, :update]
  resources :dialogs, :controller => "ideas", :type=>"Dialog",
    only: [:index, :new, :create, :show, :edit, :update]
  resources :set_pieces, :controller => "ideas", :type=>"SetPiece",
    only: [:index, :new, :create, :show, :edit, :update]
end

app/models/character.rb
class Character < Idea
  attr_accessible :mentality, :description, :name

end

app/models/dialog.rb
class Dialog < Idea

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :name, :description
  validates :name, :presence=>true
  validates :name, :uniqueness=>true
end

app/models/item.rb
class Item < Idea

end

app/models/location.rb
class Location < Idea

end

app/models/set_piece.rb
class SetPiece < Idea
  attr_accessible :start_state, :end_state, :description, :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = params[:type].present? ? idea_type.all : Idea.all
  end

  def new
    @idea = idea_type.new
  end

  def create
    @idea = idea_type.create params[params[:type].underscore.to_sym]
    
    if @idea.save
      flash[:success]="#{@idea.class.to_s.titleize} #{@idea.name} was successfully created."
      redirect_to root_url
    else
      flash.now[:error] = @idea.errors.full_messages.to_sentence
      render :action=>"new" 
    end
  end

  def show
    @idea = idea_type.find(params[:id])
  end

  def edit
    @idea = idea_type.find(params[:id])
  end

  def update
    @idea = idea_type.find(params[:id])
    @idea.update_attributes(params[params[:type].underscore.to_sym])
    if @idea.save
      flash[:success]="#{@idea.class.to_s.titleize} #{@idea.name} was successfully created."
      redirect_to root_url
    else
      flash.now[:error] = @idea.errors.full_messages.to_sentence
      render :action=>"edit" 
    end
  end

  private

  def idea_type
    params[:type].constantize
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def dom_name(object, attribute='id')
    "#{object.class.to_s.downcase}_#{object.send(attribute).gsub(/[^0-9A-Za-z\-_]/, '_')}"
  rescue
    if object.respond_to?('id')
      "#{object.class.to_s.downcase}_#{object.id}"
    else
      "#{object.class.to_s.downcase}_#{object.to_s.gsub(/[^0-9A-Za-z\-_]/, '_')}"
    end
  end
end

app/views/ideas/_character_form.slim
= form_for @idea do |f|
  = f.label :name 
  = f.text_field :name 
  br

  = f.label :description 
  = f.text_field :description
  br

  = f.label :mentality
  = f.text_field :mentality
  br

  = f.submit "Submit"

app/views/ideas/_dialog_form.slim
= form_for @idea do |f|
  = f.label :name
  = f.text_field :name
  br

  = f.label :description
  = f.text_field :description
  br

  = f.submit "Submit"

app/views/ideas/_item_form.slim
= form_for @idea do |f|
  = f.label :name
  = f.text_field :name
  br

  = f.label :description
  = f.text_field :description
  br

  = f.submit "Submit"

app/views/ideas/_location_form.slim
= form_for @idea do |f|
  = f.label :name
  = f.text_field :name
  br

  = f.label :description
  = f.text_field :description
  br

  = f.submit "Submit"

app/views/ideas/_setpiece_form.slim
= form_for @idea do |f|
  = f.label :name
  = f.text_field :name
  br

  = f.label :description
  = f.text_field :description
  br

  = f.label :start_state
  = f.text_field :start_state
  br

  = f.label :end_state
  = f.text_field :end_state
  br

  = f.submit "Submit"

app/views/ideas/edit.slim
div#content-entry
  = render "#{params[:type].downcase}_form"

app/views/ideas/index.slim
p data-role='description' This is the storied app.

div#characters
  h3 characters
  - if @ideas.any? {|i| i.class == Character}
    - @ideas.each do |character|
      - if character.class == Character
        div id="#{dom_name(character, 'name')}" 
          div.span3
            = link_to(character.name, character, :class=>'btn btn-primary btn-block') 
          = link_to('edit', edit_character_path(character), :class=>'btn btn-mini')
  - else
    p No characters yet.

div#items
  h3 items
  - if @ideas.any? {|i| i.class == Item}
    - @ideas.each do |item|
      - if item.class == Item
        div id="#{dom_name(item, 'name')}" 
          div.span3
            = link_to(item.name, item, :class=>'btn btn-primary btn-block') 
          = link_to('edit', edit_item_path(item), :class=>'btn btn-mini')
  - else
    p No items yet.

div#locations
  h3 locations
  - if @ideas.any? {|i| i.class == Location}
    - @ideas.each do |location|
      - if location.class == Location 
        div id="#{dom_name(location, 'name')}" 
          div.span3
            = link_to(location.name, location, :class=>'btn btn-primary btn-block') 
          = link_to('edit', edit_location_path(location), :class=>'btn btn-mini')
  - else
    p No locations yet.

div#dialogs
  h3 dialogs
  - if @ideas.any? {|i| i.class == Dialog}
    - @ideas.each do |dialog|
      - if dialog.class == Dialog
        div id="#{dom_name(dialog, 'name')}" 
          div.span3
            = link_to(dialog.name, dialog, :class=>'btn btn-primary btn-block') 
          = link_to('edit', edit_dialog_path(dialog), :class=>'btn btn-mini')
  - else
    p No dialogs yet.

div#set_pieces
  h3 set pieces
  - if @ideas.any? {|i| i.class == SetPiece}
    - @ideas.each do |sp|
      - if sp.class == SetPiece
        div id="#{dom_name(sp, 'name')}" 
          div.span3
            = link_to(sp.name, sp, :class=>'btn btn-primary btn-block') 
          = link_to('edit', edit_set_piece_path(sp), :class=>'btn btn-mini')
  - else
    p No set pieces yet.

app/views/ideas/new.slim
div#content-entry
  = render "#{params[:type].downcase}_form"

app/views/ideas/show.slim
div.details id="#{dom_name(@idea, 'name')}"
  p 
    #{@idea.name} (#{link_to('edit', send("edit_#{@idea.class.to_s.underscore}_path", @idea))})
  p
    span.label Description:
    = @idea.description

  - if @idea.class.accessible_attributes.include?(:mentality)
    p
      span.label Mentality:
      = @idea.mentality

  - if @idea.class.accessible_attributes.include?(:start_state)
    p
      span.label = "Start state:"
      = @idea.start_state

  - if @idea.class.accessible_attributes.include?(:end_state)
    p
      span.label = "End state:"
      = @idea.end_state

app/views/layouts/application.slim
doctype html
html
  head
  title = content_for?(:title) ? yield(:title) : "Storied"
  = stylesheet_link_tag "application"
  = javascript_include_tag "application"
  = csrf_meta_tags
  = yield(:head)

  body
    div#wrap
      div.container
        div#header.row
          h1.title 
            |Storied 
            small the idea blender

          div.span9
            div.navbar.navbar-inverse
              div.navbar-inner
                div.container
                  button.btn.btn-navbar type="button" data-toggle="collapse" data-target="#nav-collapse-01"
                  div#nav-collapse-01.nav-collapse.collapse
                    ul.nav
                      li = link_to("home", root_path)
                      li
                        = link_to("new idea", "#")
                        ul
                          li = link_to("new character", new_character_path)
                          li = link_to("new item", new_item_path)
                          li = link_to("new location", new_location_path)
                          li = link_to("new dialog", new_dialog_path)
                          li = link_to("new set piece", new_set_piece_path)

        div#content.row
          div.flash
            - flash.each do |type, message|
              div class="alert alert-#{type}"
                - if message.is_a? String
                  = message
                button.close type="button" data-dismiss="alert" &times;

          = yield

      div#push

    div#footer
      div.container
        p &copy; FourFold 2013